### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by yara-blue** [koenichiwa/const_typed_builder#65]
Hi there, I can not get your crate to compile:

rust versions tried:
```
cargo 1.73.0 (9c4383fb5 2023-08-26)
cargo 1.75.0-nightly (65e297d1e 2023-11-03)
```

<details><summary>Compile errors</summary>
<p>
   Compiling const_typed_builder_derive v0.3.0
error[E0599]: no method named `require_ident` found for reference `&syn::Path` in the current scope
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/field_info.rs:282:44
    |
282 |         let attr_ident = match attr.path().require_ident() {
    |                                            ^^^^^^^^^^^^^ help: there is a method with a similar name: `get_ident`

error[E0282]: type annotations needed
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/field_info.rs:285:17
    |
285 |                 emit_error!(ident, format!("{ident} can't be used as a field attribute"));
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
    |
    = note: this error originates in the macro `$crate::diagnostic` which comes from the expansion of the macro `emit_error` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `require_ident` found for struct `syn::Path` in the current scope
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/field_info.rs:311:46
    |
311 |             let path_ident = match meta.path.require_ident() {
    |                                              ^^^^^^^^^^^^^ help: there is a method with a similar name: `get_ident`

error[E0599]: no method named `require_ident` found for struct `syn::Path` in the current scope
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/field_info.rs:371:44
    |
371 | ...                   match path.require_ident() {
    |                                  ^^^^^^^^^^^^^ help: there is a method with a similar name: `get_ident`

error[E0599]: no method named `require_ident` found for reference `&syn::Path` in the current scope
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/struct_info.rs:212:44
    |
212 |         let attr_ident = match attr.path().require_ident() {
    |                                            ^^^^^^^^^^^^^ help: there is a method with a similar name: `get_ident`

error[E0599]: no method named `require_ident` found for struct `syn::Path` in the current scope
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/struct_info.rs:259:46
    |
259 |             let path_ident = match meta.path.require_ident() {
    |                                              ^^^^^^^^^^^^^ help: there is a method with a similar name: `get_ident`

error[E0599]: no method named `require_ident` found for struct `syn::Path` in the current scope
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/struct_info.rs:338:46
    |
338 |             let group_name = match meta.path.require_ident() {
    |                                              ^^^^^^^^^^^^^ help: there is a method with a similar name: `get_ident`

error[E0599]: no method named `require_ident` found for reference `&syn::Path` in the current scope
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/struct_info.rs:353:83
    |
353 | ...h path.require_ident() {
    |           ^^^^^^^^^^^^^ help: there is a method with a similar name: `get_ident`

error[E0599]: no method named `require_ident` found for struct `syn::Path` in the current scope
   --> /home/david/.cargo/registry/src/index.crates.io-6f17d22bba15001f/const_typed_builder_derive-0.3.0/src/info/struct_info.rs:414:49
    |
414 |                     let group_type = match path.require_ident() {
    |                                                 ^^^^^^^^^^^^^ help: there is a method with a similar name: `get_ident`
</p>
</details>

**Comment by koenichiwa** [comment]
Hi thank you so much for the bug report. I'll look into it ASAP (although I do have my thesis defense this week)

In the meantime, can you provide the crate version used and a minimal sample of the code where you derive the `Builder`?

**Comment by koenichiwa** [comment]
Oh wait I took a quick look at the compile errors. I see the crate version that you used. I also think I see where the issue might be. 

Do you use the `syn` crate in your project by any chance? If so, what is the version and what are the feature flags?

There seems to be a function that is missing, but it's in the `syn` crate behind the "parsing" feature flag. The function was also added in `v2.0.32`. 

I changed my Cargo.toml to depend on a more specific version (or higher), but I want to know for sure if this is not the only reason that you're having an issue.

If you (temporarily) add `const_typed_builder` to your dependencies like this:
```toml
[dependencies]
const_typed_builder = { git = "https://github.com/koenichiwa/const_typed_builder.git", branch = "hotfix/fix-dependencies" }
```
Then you might be able to check if it works. Could you please report back if that's what caused the issue?

**Comment by yara-blue** [comment]
The hotfix did not work (caused issues for cargo when figuring out a syn version).

I got it working by changing the syn dependency line in Cargo.toml to:

```
syn = { version = "^2.0.32", features = ["full", "extra-traits"] }
```
The ^ specifies that you need at least `2.0.32`. To be honest this is partially the fault of syn. Cargo assumes semver and patch versions are not allowed to introduce new functionality; see: https://semver.org/#spec-item-7.

Good luck on your thesis defense!

**Comment by koenichiwa** [comment]
> (caused issues for cargo when figuring out a syn version)

Can you specify which issues? Because I would prefer to depend on the latest version if ever possible of course.

> To be honest this is partially the fault of syn. Cargo assumes semver and patch versions are not allowed to introduce new functionality

Yes, good point, I might link this issue through to the `syn` repo.

The caret is the same as the default strategy by the way; see: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements

**Comment by yara-blue** [comment]
I cant seem to reproduce the issue anymore, Ill reopen if it reappears but for now it seems fixed :)

> The caret is the same as the default strategy by the way; see: [](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements)

I didn't know that thanks!

> Yes, good point, I might link this issue through to the `syn` repo.

It seems I was wrong: https://semver.org/#spec-item-4. At 0.anything you may break anything anytime.
